[package]
name = "composer"
version = "0.1.0"
authors = ["Johannes Willbold <johannes.willbold@rub.de>"]
edition = "2018"

[dependencies.compiler]
path = "../compiler"

[dev-dependencies]
test-exec = "0.1.0"

[dependencies]
resw = "*"
resast = "*"
ressa = "*"
